export const helpService = {
  text: (): string => {
    return [
      'Usage: msh [command]',
      '',
      'Command:',
      '',
      '   -i | --init             Initiate .msh config file with default values',
      '',
      '   -g | --git [option]',
      '       options:',
      '          clone            Clone all project',
      '          pull             Pull all projects',
      '          fetch            Fetch all projects',
      '          status           Get status for all projects',
      '',
      '   -n | --npm  [option]    Run npm i in all containers',
      '       options:',
      '          install          Run npm i for all projects',
      // '          global           !!!Not Implemented yet!!! Gather all npm packages to a global package.json',
      // '',
      // '   -c | --clean [option]',
      // '       options:',
      // '          npm              Clean all node_modules folders',
      // '          docker           Remove all docker images (do a "docker-compose down" command first)',
      // '',
      // '   -p | --pr               Generate PR for all projects (added option to auto merge)',
      '',
      '   -v | --version          Display cli version',
      '',
      '   -h | --help             Display this help',
    ].join('\n')
  },
}
